### ISSUE TITLE
Blank Browser Tab

### ISSUE THREAD

**Issue by subz390** [fearlessjake/wamap#2]
How to replicate: Chrome web browser > open new tab with map in it > close browser > open browser = blank page.
Expecting map to auto reload.

Comment: I can't recall the event listener, but there's one to detect when the page is in focus or when the user navigates to the tab.  I tried to Google it for you but my memory failed sorry guys.  But it should be an easy enough issue to catch so when a user opens the browser again the map automatically reloads.

**Comment by Machine-Maker** [comment]
I don't experience this issue any more.
