### ISSUE TITLE
Reference Link with short-url

### ISSUE THREAD

**Issue by subz390** [fearlessjake/wamap#4]
Any public map user can get a short url link to a point on the map.  This short url can be copy and pasted in-game chat, discord, email, social media etc.  The link when pasted into a browser will open the map and drop a marker at that location for easy reference.
You could take this feature a few steps further by allowing the user to manage markers stored client-side in a cookie.  These can be used for any number of useful purposes, for example; favourite loot spots, where the ship was logged off, a reminder of where to start again, things like that.
From a community perspective, event organisers can share the map location of their event, users can share map point location with Bossa in technical support emails.

**Comment by subz390** [comment]
I mean anywhere on the map, not just an island reference....

**Comment by subz390** [comment]
I saw how you added a reference link to islands which is awesome, so I extended the idea to dropping pins on the map.

**Comment by Machine-Maker** [comment]
added reference links to icons. still exploring storing locations per client.

**Comment by Machine-Maker** [comment]
added characters
