### ISSUE TITLE
Graceful handling of 404 messages

### ISSUE THREAD

**Issue by subz390** [fearlessjake/wamap#5]
I just did a random test to see the result of browsing the images folder on the server.
https://surveyor.cardinalguild.com/images/islands/

..and was met with debugging info.
![servermessages](https://user-images.githubusercontent.com/11546815/48727160-580f1d80-ec29-11e8-89b8-3edbe72fdfad.png)

I think it would be safer (security concerns) as well as friendlier if the response was redirection to home page or a generic pretty 404 message.

**Comment by fearlessjake** [comment]
Fixed
