### ISSUE TITLE
data.cardinalguild.com cannot handle CORS-preflight OPTIONS request

### ISSUE THREAD

**Issue by krugar** [fearlessjake/wamap#7]
Ahoy mateys, these be great maps yer makin'! :+1: 
Thanks a lot for your work here, much appreciated!

However, it appears that the Varnish server at data.cardinalguild.com fails to answer the CORS-preflight OPTIONS request, leading to an empty map when viewed in Firefox (it works in Chrome). The Nginx running at surveyor.cardinalguild.com is configured to correctly reply to the request, so I'm assuming you understand the problem. [Link to relevant CORS documentaton](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin), just in case :) Sadly I have no experience with Varnish (and/or Fastly?), hence no tips there.

---

Steps to reproduce: open the map in firefox.

Console output on firefox:
```
13:48:25.302 Service workers are not supported. fb3f8b68867fac4ed6f5.js:1:2774
13:48:25.510 Loading islands from surveyor.cardinalguild fb3f8b68867fac4ed6f5.js:1:7417
13:48:26.370 Island data loaded fb3f8b68867fac4ed6f5.js:1:5662
13:48:26.392 Loading map boundaries fb3f8b68867fac4ed6f5.js:1:7627
13:48:26.506 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://data.cardinalguild.com/wamap.geojson. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).[Learn More]
13:48:26.506 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://data.cardinalguild.com/wamap.geojson. (Reason: CORS request did not succeed).[Learn More]
13:48:26.509
Unhandled promise rejection Error: "Network Error"
	exports https://map.cardinalguild.com/_nuxt/0eabee45f833bff54278.js:2:128036
	onerror https://map.cardinalguild.com/_nuxt/0eabee45f833bff54278.js:2:127091
0eabee45f833bff54278.js:2:151207
```

Request headers on the OPTIONS request that fails:
```
Host: data.cardinalguild.com
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:63.0) Gecko/20100101 Firefox/63.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Access-Control-Request-Method: GET
Origin: https://map.cardinalguild.com
DNT: 1
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
TE: Trailers
```
corresponding Response headers:
```
HTTP/2.0 405 Method Not Allowed
server: Varnish
retry-after: 0
content-type: 
accept-ranges: bytes
date: Fri, 30 Nov 2018 12:48:32 GMT
via: 1.1 varnish
x-served-by: cache-hhn1546-HHN
x-cache: MISS
x-cache-hits: 0
x-timer: S1543582113.528730,VS0,VE0
x-fastly-request-id: 6b06279fb38da796f814ff53647fd4ae5e20488a
content-length: 131
X-Firefox-Spdy: h2
```

**Comment by fearlessjake** [comment]
I am aware about this, apparently this is because github pages removes the CORS header after 4000 requests.  To limit and save their bandwidth.

I will be implemting ways and have a failover system for this.

**Comment by krugar** [comment]
Cheers. Only noticed you were redirecting to GitHub after I wrote this. I know they don't like to be used as an API endpoint, but there's next to no documentation on the topic.

In the meantime, maybe add a little notice to the landing page that Chrome is the preferred browser?

**Comment by fearlessjake** [comment]
Yeah we could add http://outdatedbrowser.com/en

My focus is now getting the reporting fixed
